name: fixed
version: 4.0.1
homepage: https://github.com/onepub-dev/fixed
documentation: https://fixed.onepub.dev
description: Fixed scale decimal numbers with mathematical operations, formatting and parsing.
repository: https://github.com/onepub-dev/fixed
environment: 
  sdk: '>=3.0.0 <4.0.0'
dependencies: 
  decimal: ^2.3.3
  intl: ^0.19.0
  meta: ^1.10.0
dev_dependencies: 
  lint_hard: ^4.0.0
  test: ^1.25.2
